
// pet_id chart:
// number index for ref: [0][1][2][3],
// [0] - 'class' ex: mammal;
// [1] - 'family' ex: felidae;
// [2] - 'genus' ex: panthera;
// [3] - 'no.' ex: Tiger... just the count of that 'family' of animal;
//                 [0]      [1]     [2]    [3]
// ex: |1137| -> Mammal, Felidae, Puma, Cougar... this is a Cougar
//
// > CLASS chart:
// 1 -> Mammal
// 2 -> Aves 'birds'
// 3 -> Actinopterygii 'deep sea fish'
// 4 -> Reptilia



const pets = [
  {
    "pet_id":"1111",
    "class":"mammal",
    "family":"Felidae",
    "genus":"Panthera",
    "species":"Tiger",
    "price":"48,000"
  },
  {
    "pet_id":"1112",
    "class":"mammal",
    "family":"Felidae",
    "genus":"Panthera",
    "species":"Lion",
    "price":"50,000"
  },
  {
    "pet_id":"1113",
    "class":"mammal",
    "family":"Felidae",
    "genus":"Panthera",
    "species":"Jaguar",
    "price":"39,000"
  },
  {
    "pet_id":"1114",
    "class":"mammal",
    "family":"Felidae",
    "genus":"Panthera",
    "species":"Leopard",
    "price":"37,000"
  },
  {
    "pet_id":"1115",
    "class":"mammal",
    "family":"Felidae",
    "genus":"Panthera",
    "species":"Snow Leopard",
    "price":"44,000"
  },
  {
    "pet_id":"1126",
    "class":"mammal",
    "family":"Felidae",
    "genus":"Acinonyx",
    "species":"Cheeta",
    "price":"47,000"
  },
  {
    "pet_id":"1137",
    "class":"mammal",
    "family":"Felidae",
    "genus":"Puma",
    "species":"Cougar",
    "price":"29,000"
  },
  {
    "pet_id":"1218",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Urocyon",
    "species":"Island Fox",
    "price":"13,500",
  },
  {
    "pet_id":"1229",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Vulpini",
    "species":"Raccoon Dog",
    "price":"7,500",
  },
  {
    "pet_id":"12210",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Vulpini",
    "species":"Arctic Fox",
    "price":"15,750",
  },
  {
    "pet_id":"12211",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Vulpini",
    "species":"Blanford's Fox",
    "price":"10,350",
  },
  {
    "pet_id":"12212",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Vulpini",
    "species":"Bat-Eared Fox",
    "price":"11,450",
  },
  {
    "pet_id":"12213",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"Hoary Fox",
    "price":"8,550",
  },
  {
    "pet_id":"12214",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"Bush Dog",
    "price":"6,000",
  },
  {
    "pet_id":"12215",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"Crab-Eating Fox",
    "price":"7,200",
  },
  {
    "pet_id":"12216",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"African Wild Dog",
    "price":"13,100",
  },
  {
    "pet_id":"12217",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"Ethiopian Wolf",
    "price":"13,550",
  },
  {
    "pet_id":"12218",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"Coyote",
    "price":"3,050",
  },
  {
    "pet_id":"12219",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"Side-Striped Jackal",
    "price":"2,350",
  },
  {
    "pet_id":"12220",
    "class":"mammal",
    "family":"Canidae",
    "genus":"Canini",
    "species":"Gray Wolf",
    "price":"8,750",
  },
  {
    "pet_id":"13121",
    "class":"mammal",
    "family":"Balaenopteridae",
    "genus":"Balaenoptera",
    "species":"Blue Whale",
    "price":"597,750",
  },
  {
    "pet_id":"13122",
    "class":"mammal",
    "family":"Balaenopteridae",
    "genus":"Balaenoptera",
    "species":"Fin Whale",
    "price":"345,500",
  },
  {
    "pet_id":"13123",
    "class":"mammal",
    "family":"Balaenopteridae",
    "genus":"Balaenoptera",
    "species":"Antarctic Minke Whale",
    "price":"270,500",
  },
  {
    "pet_id":"13124",
    "class":"mammal",
    "family":"Balaenopteridae",
    "genus":"Megaptera",
    "species":"Humpback Whale",
    "price":"330,900",
  },
  {
    "pet_id":"14125",
    "class":"mammal",
    "family":"Equidae",
    "genus":"Equus",
    "species":"Zebra",
    "price":"30,200",
  },
  {
    "pet_id":"14126",
    "class":"mammal",
    "family":"Equidae",
    "genus":"Equus",
    "species":"African Wild Ass",
    "price":"25,000",
  },
  {
    "pet_id":"14127",
    "class":"mammal",
    "family":"Equidae",
    "genus":"Equus",
    "species":"Przewalski's Horse",
    "price":"19,750",
  },
  {
    "pet_id":"14128",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ursus",
    "species":"Kodiak Brown Bear",
    "price":"23,300",
  },
  {
    "pet_id":"14129",
    "class":"mammal",
    "family":"Equidae",
    "genus":"Equus",
    "species":"Kiang",
    "price":"27,750",
  },
  {
    "pet_id":"14130",
    "class":"mammal",
    "family":"Equidae",
    "genus":"Equus",
    "species":"Nubian Wild Ass",
    "price":"17,050",
  },
  {
    "pet_id":"15131",
    "class":"mammal",
    "family":"Hippopotamidae",
    "genus":"Choeropsis",
    "species":"Pygmy Hippopotamus",
    "price":"36,250",
  },
  {
    "pet_id":"15232",
    "class":"mammal",
    "family":"Hippopotamidae",
    "genus":"Hippopotamus",
    "species":"Hippopotamus",
    "price":"46,250",
  },
  {
    "pet_id":"16133",
    "class":"mammal",
    "family":"Camelidae",
    "genus":"Lama",
    "species":"Llama",
    "price":"22,250",
  },
  {
    "pet_id":"16134",
    "class":"mammal",
    "family":"Camelidae",
    "genus":"Lama",
    "species":"Guanaco",
    "price":"20,775",
  },
  {
    "pet_id":"16235",
    "class":"mammal",
    "family":"Camelidae",
    "genus":"Camelus",
    "species":"Bactrian camel",
    "price":"31,475",
  },
  {
    "pet_id":"16236",
    "class":"mammal",
    "family":"Camelidae",
    "genus":"Camelus",
    "species":"Dromedary",
    "price":"36,275",
  },
  {
    "pet_id":"16337",
    "class":"mammal",
    "family":"Camelidae",
    "genus":"Vicugna",
    "species":"Alpaca",
    "price":"17,575",
  },
  {
    "pet_id":"16338",
    "class":"mammal",
    "family":"Camelidae",
    "genus":"Vicugna",
    "species":"Vicuña",
    "price":"19,775",
  },
  {
    "pet_id":"17139",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Sus",
    "species":"Bearded Pig",
    "price":"4,765",
  },
  {
    "pet_id":"17140",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Sus",
    "species":"Visayan Warty Pig",
    "price":"8,765",
  },
  {
    "pet_id":"17141",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Sus",
    "species":"Javan Warty Pig",
    "price":"6,055",
  },
  {
    "pet_id":"17142",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Sus",
    "species":"Wild Boar",
    "price":"10,055",
  },
  {
    "pet_id":"17243",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Phacochoerus",
    "species":"Common Warthog",
    "price":"13,525",
  },
  {
    "pet_id":"17244",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Phacochoerus",
    "species":"Desert Warthog",
    "price":"11,150",
  },
  {
    "pet_id":"17345",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Babyrousa",
    "species":"North Sulawesi Babirusa",
    "price":"14,550",
  },
  {
    "pet_id":"17446",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Potamochoerus",
    "species":"Red River Hog",
    "price":"9,200",
  },
  {
    "pet_id":"17547",
    "class":"mammal",
    "family":"Suidae",
    "genus":"Porcula",
    "species":"Pygmy Hog",
    "price":"13,250",
  },
  {
    "pet_id":"18148",
    "class":"mammal",
    "family":"Hominidae",
    "genus":"Pongo",
    "species":"Sumatran Orangutan",
    "price":"44,250",
  },
  {
    "pet_id":"18249",
    "class":"mammal",
    "family":"Hominidae",
    "genus":"Gorilla",
    "species":"Western Gorilla",
    "price":"67,975",
  },
  {
    "pet_id":"18250",
    "class":"mammal",
    "family":"Hominidae",
    "genus":"Gorilla",
    "species":"Eastern Gorilla",
    "price":"69,980",
  },
  {
    "pet_id":"18350",
    "class":"mammal",
    "family":"Hominidae",
    "genus":"Pan",
    "species":"Bonobo",
    "price":"22,480",
  },
  {
    "pet_id":"18351",
    "class":"mammal",
    "family":"Hominidae",
    "genus":"Pan",
    "species":"Common Chimpanzee",
    "price":"24,400",
  },
  {
    "pet_id":"18452",
    "class":"mammal",
    "family":"Hominidae",
    "genus":"Symphalangus",
    "species":"Siamang",
    "price":"17,800",
  },
  {
    "pet_id":"18553",
    "class":"mammal",
    "family":"Hominidae",
    "genus":"Hylobates",
    "species":"Agile Gibbon",
    "price":"14,250",
  },
  {
    "pet_id":"19154",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ailuropoda",
    "species":"Giant Panda",
    "price":"67,350",
  },
  {
    "pet_id":"19255",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Tremarctos",
    "species":"Spectacled Bear",
    "price":"54,750",
  },
  {
    "pet_id":"19356",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ursus",
    "species":"Polar Bear",
    "price":"97,745",
  },
  {
    "pet_id":"19357",
    "class":"mammal",
    "family":"Phascolarctidae",
    "genus":"Phascolarctos",
    "species":"Koala Bear",
    "price":"42,450",
  },
  {
    "pet_id":"19358",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ursus",
    "species":"Cinnamon Bear",
    "price":"81,355",
  },
  {
    "pet_id":"19359",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ursus",
    "species":"Glacier Bear",
    "price":"81,355",
  },
  {
    "pet_id":"19360",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ursus",
    "species":"Baluchistan Black Bear",
    "price":"68,300",
  },
  {
    "pet_id":"19361",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ursus",
    "species":"Japanese Black Bear",
    "price":"72,500",
  },
  {
    "pet_id":"19362",
    "class":"mammal",
    "family":"Ursidae",
    "genus":"Ursus",
    "species":"Ussuri Black Bear",
    "price":"59,900",
  },
  {
    "pet_id":"10163",
    "class":"mammal",
    "family":"Odobenidae",
    "genus":"Odobenus",
    "species":"Walrus",
    "price":"234,979",
  },
  {
    "pet_id":"10164",
    "class":"mammal",
    "family":"Monodontidae",
    "genus":"Monodon",
    "species":"Walrus",
    "price":"537,670",
  },
  {
    "pet_id":"10165",
    "class":"mammal",
    "family":"Cervidae",
    "genus":"Hydropotes",
    "species":"Water Deer",
    "price":"109,000",
  },
  {
    "pet_id":"10166",
    "class":"mammal",
    "family":"Giraffidae",
    "genus":"Giraffa",
    "species":"Giraffe",
    "price":"123,050",
  },
  {
    "pet_id":"10167",
    "class":"mammal",
    "family":"Giraffidae",
    "genus":"Okapia",
    "species":"Okapi",
    "price":"42,150",
  },
  {
    "pet_id":"10168",
    "class":"mammal",
    "family":"Bovidae",
    "genus":"Bos",
    "species":"Gaur",
    "price":"47,555",
  },
  {
    "pet_id":"10169",
    "class":"mammal",
    "family":"Bovidae",
    "genus":"Bos",
    "species":"Zebu",
    "price":"23,595",
  },
  {
    "pet_id":"10170",
    "class":"mammal",
    "family":"Bovidae",
    "genus":"Bos",
    "species":"Wild Yak",
    "price":"25,155",
  },
  {
    "pet_id":"10171",
    "class":"mammal",
    "family":"Cervidae",
    "genus":"Rangifer",
    "species":"Reindeer",
    "price":"63,150",
  },
  {
    "pet_id":"10172",
    "class":"mammal",
    "family":"Cervidae",
    "genus":"Odocoileus",
    "species":"White-Tailed Deer",
    "price":"2,560",
  },
  {
    "pet_id":"10173",
    "class":"mammal",
    "family":"Cervidae",
    "genus":"Alces",
    "species":"Moose",
    "price":"13,720",
  },
  {
    "pet_id":"4111",
    "class":"Reptilia",
    "family":"Crocodylidae",
    "genus":"Crocodylus",
    "species":"Freshwater Crocodile",
    "price":"24,700",
  },
  {
    "pet_id":"4112",
    "class":"Reptilia",
    "family":"Crocodylidae",
    "genus":"Crocodylus",
    "species":"Mugger Crocodile",
    "price":"26,340",
  },
  {
    "pet_id":"4113",
    "class":"Reptilia",
    "family":"Crocodylidae",
    "genus":"Crocodylus",
    "species":"American Crocodile",
    "price":"22,510",
  },
  {
    "pet_id":"4114",
    "class":"Reptilia",
    "family":"Crocodylidae",
    "genus":"Crocodylus",
    "species":"Saltwater Crocodile",
    "price":"29,100",
  },
  {
    "pet_id":"4215",
    "class":"Reptilia",
    "family":"Alligatoridae",
    "genus":"Caiman",
    "species":"Broad-Snouted Caiman",
    "price":"32,690",
  },
  {
    "pet_id":"4216",
    "class":"Reptilia",
    "family":"Alligatoridae",
    "genus":"Caiman",
    "species":"Yacare Caiman",
    "price":"33,240",
  },
  {
    "pet_id":"4227",
    "class":"Reptilia",
    "family":"Alligatoridae",
    "genus":"Alligator",
    "species":"American Alligator",
    "price":"46,990",
  },
  {
    "pet_id":"4228",
    "class":"Reptilia",
    "family":"Alligatoridae",
    "genus":"Alligator",
    "species":"Chinese Alligator",
    "price":"38,465",
  },
  {
    "pet_id":"4239",
    "class":"Reptilia",
    "family":"Alligatoridae",
    "genus":"Paleosuchus",
    "species":"Cuvier's Dwarf Caiman",
    "price":"23,565",
  },
  {
    "pet_id":"42310",
    "class":"Reptilia",
    "family":"Alligatoridae",
    "genus":"Paleosuchus",
    "species":"Smooth-Fronted Caiman",
    "price":"21,255",
  },
  {
    "pet_id":"42411",
    "class":"Reptilia",
    "family":"Alligatoridae",
    "genus":"Melanosuchus",
    "species":"Black Caiman",
    "price":"28,425",
  },
  {
    "pet_id":"43112",
    "class":"Reptilia",
    "family":"Gavialidae",
    "genus":"Tomistoma",
    "species":"False Gharial",
    "price":"33,375",
  },
  {
    "pet_id":"44113",
    "class":"Reptilia",
    "family":"Pythonidae",
    "genus":"Python",
    "species":"Burmese Python",
    "price":"7,275",
  },
  {
    "pet_id":"45114",
    "class":"Reptilia",
    "family":"Boidae",
    "genus":"Boa",
    "species":"Boa Constrictor",
    "price":"12,100",
  },
  {
    "pet_id":"45215",
    "class":"Reptilia",
    "family":"Boidae",
    "genus":"Eunectes",
    "species":"Green Anaconda",
    "price":"15,670",
  },
  {
    "pet_id":"45216",
    "class":"Reptilia",
    "family":"Boidae",
    "genus":"Eunectes",
    "species":"Bolivian Anaconda",
    "price":"17,470",
  },
  {
    "pet_id":"46117",
    "class":"Reptilia",
    "family":"Viperidae",
    "genus":"Montivipera",
    "species":"Central Turkish Mountain Viper",
    "price":"12,850",
  },
  {
    "pet_id":"2111",
    "class":"Aves",
    "family":"Struthionidae",
    "genus":"Struthio",
    "species":"Ostrich",
    "price":"11,000"
  },
  {
    "pet_id":"2222",
    "class":"Aves",
    "family":"Apterygidae",
    "genus":"Apteryx",
    "species":"Kiwi",
    "price":"2,000"
  },
  {
    "pet_id":"2333",
    "class":"Aves",
    "family":"Anatidae",
    "genus":"Anas",
    "species":"Steamer Duck",
    "price":"1,200"
  },
  {
    "pet_id":"2344",
    "class":"Aves",
    "family":"Anatidae",
    "genus":"Cygnus",
    "species":"Mute swan",
    "price":"4,500"
  },
  {
    "pet_id":"2345",
    "class":"Aves",
    "family":"Anatidae",
    "genus":"Cygnus",
    "species":"Trumpeter swan",
    "price":"6,300"
  },
  {
    "pet_id":"2356",
    "class":"Aves",
    "family":"Anatidae",
    "genus":"Hymenolaimus",
    "species":"Blue Duck",
    "price":"2,500"
  },
  {
    "pet_id":"2337",
    "class":"Aves",
    "family":"Anatidae",
    "genus":"Anas",
    "species":"Mallard",
    "price":"1,300"
  },
  { 
    "pet_id":"2338",
    "class":"Aves",
    "family":"Anatidae",
    "genus":"Anas",
    "species":"Yellow-Billed Duck",
    "price":"2,600"
  },
  { 
    "pet_id":"2339",
    "class":"Aves",
    "family":"Anatidae",
    "genus":"Anas",
    "species":"Hawaiian duck",
    "price":"2,800"
  },
  { 
    "pet_id":"24110",
    "class":"Aves",
    "family":"Sulidae",
    "genus":"Sula",
    "species":"Blue-Footed Booby",
    "price":"203,560"
  },
  { 
    "pet_id":"3111",
    "class":"Actinopterygii",
    "family":"Melanocetidae",
    "genus":"Melanocetus",
    "species":"Humpback Anglerfish",
    "price":"129,880"
  },
  { 
    "pet_id":"3212",
    "class":"Actinopterygii",
    "family":"Stomiidae",
    "genus":"Chauliodus",
    "species":"Viperfish",
    "price":"109,880"
  },
];


module.exports = {
  pets
}
