DROP DATABASE IF EXISTS purchase;
USE purchase;

DROP TABLE IF EXISTS items;
CREATE TABLE items 
(
  id INTEGER NOT NULL AUTO_INCREMENT,
  item_name VARCHAR(48) UNIQUE NOT NULL,
  price INTEGER NOT NULL,
)